import './js/app';

import './css/reset.css';
import './css/fonts.css';
import './css/bread-crumbs.css';
import './css/index.css';
import './css/header.css';
import './css/footer.css';
import './css/page-product-card.css';
import './css/synergy-&-style-lights.css';
import './css/slider-product-card.css';
import './css/swiper-slider.css';
import './css/ssl-collections-all.css';
import './css/porcelain-synergy.css'; 
import './css/aside-filter.css';
import './css/product-line-lifestyle.css';
import './css/number-pages.css';
import './css/pdf-catalog.css';
import './css/decor.css';
